import random

ugen=[] 
 
for infinix in range(1000):
	rr = random.randint; rc = random.choice
	a = ['X572','X572-LTE']
	b = ['X604','X604B']
	c = ['X690B','X690']
	d = ['Infinix X692','MZ-Infinix X692']
	e = ['X683','X683B']
	f = ['S2 Pro','S2']
	g = ['X626','X626B','X610B','X626B LTE']
	h = ['Infinix X657','Infinix X657C','MZ-Infinix X657C']
	i = ['X6511B','X6511','X6511E']
	j = ['X6815','X6815B']
	k = ['X6810','X6811','X6811B']
	l = ['X688C','X688B']
	m = ['X659B','PR652B','X658E','PR652C','X658B']
	n = ['X689B','X689','X689D']
	o = ['X662','X662B','X689F']
	p = ['X6812','X6812B']
	q = ['X6817','X6817B']
	r = ['X6817','X6816C','X6816']
	s = ['X665B','X665']
	t = ['X6826','X6826B','X6826C']
	u = ['X666','X666B']
	v = ['X665C','X665E']
	w = ['X559C','X559','X559F']
	x = ['X606D','X606C','X606','X606B']
	# <----------[Infinix NOTE 3]----------->
	a1 = f"Mozilla/5.0 (Linux; Android {str(rr(5,9))}.0; Infinix_X601_LTE Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/95.0.4638.74 Mobile Safari/537.36"
	# <----------[Infinix NOTE 3 Pro]------->
	a2 = f"Mozilla/5.0 (Linux; Android {str(rr(5,9))}.0; Infinix NOTE 3 Pro Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/106.0.5249.126 Mobile Safari/537.36"
	# <----------[Infinix Note 30 Pro]----------->
	a3 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix X678B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/118.0.0.0 Mobile Safari/537.36"
	# <----------[Infinix Note 30 VIP]------------>
	a4 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix X6710 Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36"
	# <----------[Infinix Note 30i]------------->
	a5 = "Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix X6716B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.128 Mobile Safari/537.36"
	# <----------[Infinix Note 4]------------>
	a6 = f"Mozilla/5.0 (Linux; Android {str(rr(5,9))}.1.0; Infinix {str(rc(a))} Build/O11019; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/choicerome/108.0.5359.128 Mobile Safari/537.36"
	# <----------[Infinix Note 4 Pro]---------->
	a7 = f"Mozilla/5.0 (Linux; Android 7.0; Infinix X571 Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/112.0.5615.136 Mobile Safari/537.36"
	# <----------[Infinix Note 5]---------->
	a8 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix {str(rc(b))} Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/97.0.4692.98 Mobile Safari/537.36"
	# <----------[Infinix Note 5 Stylus]------------>
	a9 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix X605 Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36"
	# <-----------[Infinix Note 6]---------->
	a10 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix X610B Build/PPR1.180610.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/99.0.4844.88 Mobile Safari/537.36"
	# <-----------[Infinix Note 7]---------->
	a11 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix {str(rc(c))} Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/90.0.4430.91 Mobile Safari/537.36"
	#<-----------[Infinix Note 7 Lite]--------->
	a12 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix X656 Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/112.0.5615.101 Mobile Safari/537.36"
	# <----------[Infinix Note 8]---------->
	a13 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; {str(rc(d))} Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/107.0.5304.105 Mobile Safari/537.36"
	# <----------[Infinix Note 8i]--------->
	a14 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix {str(rc(e))} Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/115.0.5790.177 Mobile Safari/537.36"
	# <----------[Infinix Race Jet]------->
	a15 = f"Mozilla/5.0 (Linux; Android 7.0; Infinix X5010 Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/59.0.3071.125 Mobile Safari/537.36"
	# <---------[Infinix s2]--------->
	a16 = f"Mozilla/5.0 (Linux; Android 7.0; Infinix S2 Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.79 Mobile Safari/537.36"
	# <---------[Infinix s2 pro]------>
	a17 = f"Mozilla/5.0 (Linux; Android 6.0; Infinix {str(rc(f))} Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.71 Mobile Safari/537.36"
	# <---------[Infinix S4]------->
	a18 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix {str(rc(g))} Build/PPR1.180610.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.128 Mobile Safari/537.36"
	# <--------[Infinix Smart 4 Plus]-------->
	a19 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix X680D Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/80.0.3987.99 Mobile Safari/537.36"
	# <--------[Infinix Smart 5]-------->
	a20 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; {str(rc(h))} Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/104.0.5112.97 Mobile Safari/537.36"
	# <--------[Infinix Smart 6]-------->
	a21 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix {str(rc(i))} Build/RP1A.201005.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.71 Mobile Safari/537.36"
	# <--------[Infinix Smart 6 HD]-------->
	a22 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix X6512 Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/110.0.5481.65 Mobile Safari/537.36"
	# <--------[Infinix Smart 6 Plus]-------->
	a22 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix X6823C Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/111.0.5563.116 Mobile Safari/537.36"
	# <--------[Infinix Smart 7]-------->
	a23 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix X6515 Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/114.0.5735.131 Mobile Safari/537.36"
	# <--------[Infinix Smart 7 HD]-------->
	a24 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix X6516 Build/SP1A.210812.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/115.0.5790.166 Mobile Safari/537.36"
	# <--------[Infinix Smart 7 Plus]-------->
	a25 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix X6517 Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/105.0.5195.136 Mobile Safari/537.36"
	# <--------[Infinix Smart HD (2021)]-------->
	a26 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix X6517 Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/105.0.5195.136 Mobile Safari/537.36"
	# <--------[Infinix X6711]-------->
	a27 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix X6711 Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/118.0.0.0 Mobile Safari/537.36"
	# <--------[Infinix Zero 30 5G]-------->
	a28 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix X6731 Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/121.0.6167.157 Mobile Safari/537.36"
	# <--------[Infinix Zero 20]-------->
	a29 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix X6821 Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/114.0.5735.196 Mobile Safari/537.36"
	# <--------[Infinix Zero 3]-------->
	a30 = f"Mozilla/5.0 (Linux; Android {str(rr(5,9))}.0; Infinix Zero 3 Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/106.0.5249.126 Mobile Safari/537.36"
	# <--------[Infinix Zero 30]-------->
	a31 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix X6731B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/121.0.6167.84 Mobile Safari/537.36"
	# <--------[Infinix Zero 4]-------->
	a32 = f"Mozilla/5.0 (Linux; Android {str(rr(5,9))}.0; Infinix Zero 4 Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/56.0.2924.87 Mobile Safari/537.36"
	# <--------[Infinix Zero 4 Plus]-------->
	a33 = f"Mozilla/5.0 (Linux; Android {str(rr(5,9))}.1.1; Infinix Zero 4 Plus Build/NMF26O; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/107.0.5304.141 Mobile Safari/537.36"
	# <--------[Infinix Zero 5]-------->
	a34 = f"Mozilla/5.0 (Linux; Android {str(rr(5,9))}.0; Infinix X603 Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/112.0.5615.135 Mobile Safari/537.36"
	# <--------[Infinix Zero 5G]-------->
	a35 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix {str(rc(j))} Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/94.0.4606.85 Mobile Safari/537.36"
	# <--------[Infinix Zero 6]-------->
	a36 = f"Mozilla/5.0 (Linux; Android {str(rr(5,9))}.1.0; Infinix X620B Build/OPM1.171019.026; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/111.0.5563.116 Mobile Safari/537.36"
	# <--------[Infinix Zero 6 Pro]-------->
	a37 = f"Mozilla/5.0 (Linux; Android {str(rr(5,9))}.1.0; Infinix X620 Build/OPM1.171019.026; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/69.0.3497.100 Mobile Safari/537.36"
	#<--------[Infinix Zero 8]---------->
	a38 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix X687 Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/105.0.5195.136 Mobile Safari/537.36"
	#<--------[Infinix Zero 8i]---------->
	a39 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix X687B Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/113.0.5672.173 Mobile Safari/537.36"
	#<--------[Infinix Zero Ultra]---------->
	a40 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix X6820 Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.207 Mobile Safari/537.36"
	#<--------[Infinix Zero X]---------->
	a41 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix X6811B Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/110.0.5481.153 Mobile Safari/537.36"
	#<--------[Infinix Zero X Neo]---------->
	a42 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix X6810 Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/100.0.4896.127 Mobile Safari/537.36"
	#<--------[Infinix Zero X Pro]---------->
	a43 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix {str(rc(k))} Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/100.0.4896.127 Mobile Safari/537.36"
	#<--------[infinix gt 10 pro]------->
	a44 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix X6739 Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.43 Mobile Safari/537.36"
	#<--------[Infinix Hot 10]---------->
	a45 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix X682B Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/105.0.5195.136 Mobile Safari/537.36"
	#<--------[Infinix Hot 10 Play]---------->
	a46 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix {str(rc(l))} Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.129 Mobile Safari/537.36"
	#<--------[Infinix Hot 10i]---------->
	a47 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix {str(rc(m))} Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/110.0.5481.154 Mobile Safari/537.36"
	#<--------[Infinix Hot 10s]---------->
	a48 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix {str(rc(n))} Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/105.0.5195.136 Mobile Safari/537.36"
	#<--------[Infinix Hot 10s NFC]---------->
	a49 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix X689D Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36"
	#<--------[Infinix Hot 10T]---------->
	a50 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix X689C Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/105.0.5195.136 Mobile Safari/537.36"
	#<--------[Infinix Hot 11]---------->
	a51 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix {str(rc(o))} Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.144 Mobile Safari/537.36"
	#<--------[Infinix Hot 11 (2020)]---------->
	a52 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix X675 Build/RP1A.201005.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/113.0.5672.131 Mobile Safari/537.36"
	#<--------[Infinix Hot 11S]---------->
	a53 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix {str(rc(p))} Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/104.0.5112.97 Mobile Safari/537.36"
	#<--------[Infinix Hot 12]---------->
	a54 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix {str(rc(q))} Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/110.0.5481.153 Mobile Safari/537.36"
	#<--------[Infinix Hot 12 Play]---------->
	a55 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix {str(rc(r))} Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/104.0.5112.97 Mobile Safari/537.36"
	#<--------[Infinix Hot 12 Play NFC]---------->
	a56 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix X6816D Build/RP1A.201005.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/114.0.5735.130 Mobile Safari/537.36"
	#<-----------[Infinix Hot 12 Pro]-------------->
	a57 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix X668C Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/112.0.5615.135 Mobile Safari/537.36"
	#<-----------[Infinix Hot 12i]-------------->
	a58 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix {str(rc(s))} Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/107.0.5304.141 Mobile Safari/537.36"
	#<-----------[Infinix Hot 2]-------------->
	a59 = f"Mozilla/5.0 (Linux; Android {str(rr(5,9))}.0; Infinix X510 Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/106.0.5249.126 Mobile Safari/537.36"
	#<-----------[Infinix Hot 20]-------------->
	a60 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix {str(rc(t))} Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/114.0.5735.227 Mobile Safari/537.36"
	#<-----------[Infinix Hot 20 5G]-------------->
	a61 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix {str(rc(u))} Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/112.0.5615.136 Mobile Safari/537.36"
	#<-----------[Infinix Hot 20 Play]-------------->
	a62 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix X6825 Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/117.0.0.0 Mobile Safari/537.36"
	#<-----------[Infinix Hot 20i]-------------->
	a63 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix {str(rc(v))} Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.79 Mobile Safari/537.36"
	#<-----------[Infinix Hot 20S]-------------->
	a64 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix X6827 Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36"
	#<-----------[Infinix Hot 3]-------------->
	a65 = f"Mozilla/5.0 (Linux; Android {str(rr(5,9))}.1; Infinix HOT 3 Build/LMY47I; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/95.0.4638.74 Mobile Safari/537.36"
	#<-----------[Infinix Hot 3 Pro]-------------->
	a66 = f"Mozilla/5.0 (Linux; Android {str(rr(5,9))}.1; Infinix HOT 3 Pro Build/LMY47I; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/95.0.4638.74 Mobile Safari/537.36"
	#<-----------[Infinix Hot 30]-------------->
	a67 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix X6833B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.128 Mobile Safari/537.36"
	#<-----------[Infinix Hot 30 5G]-------------->
	a68 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix X6832 Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/121.0.6167.164 Mobile Safari/537.36"
	#<-----------[Infinix Hot 30 Play]-------------->
	a69 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix X6835 Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/117.0.0.0 Mobile Safari/537.36"
	#<-----------[Infinix Hot 30i]-------------->
	a70 = f"Mozilla/5.0 (Linux; Android {str(rr(9,15))}; Infinix X669 Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/114.0.5735.196 Mobile Safari/537.36"
	#<-----------[Infinix Hot 4]-------------->
	a71 = f"Mozilla/5.0 (Linux; Android {str(rr(5,9))}.0; Infinix HOT 4 Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/97.0.4692.87 Mobile Safari/537.36"
	#<-----------[Infinix Hot 4 Lite]-------------->
	a72 = f"Mozilla/5.0 (Linux; Android {str(rr(5,9))}.0; Infinix HOT 4 Lite Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/55.0.2883.91 Mobile Safari/537.36"
	#<-----------[Infinix Hot 4 Pro]-------------->
	a73 = f"Mozilla/5.0 (Linux; Android {str(rr(5,9))}.0; Infinix HOT 4 Pro Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/106.0.5249.126 Mobile Safari/537.36"
	#<-----------[Infinix Hot 5]-------------->
	a74 = f"Mozilla/5.0 (Linux; Android {str(rr(5,9))}.0; Infinix {str(rc(w))} Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/79.0.3945.116 Mobile Safari/537.36"
	#<-----------[Infinix Hot 5 Lite]-------------->
	a75 = f"Mozilla/5.0 (Linux; Android {str(rr(5,9))}.0; Infinix X559 Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.79 Mobile Safari/537.36"
	#<-----------[Infinix Hot 6]-------------->
	a76 = f"Mozilla/5.0 (Linux; Android {str(rr(5,9))}.1.0; Infinix {str(rc(x))} Build/O11019) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.73 Mobile Safari/537.36"
	#<-----------[Infinix Hot 6 Pro]-------------->
	a77 = f"Mozilla/5.0 (Linux; Android {str(rr(5,9))}.0.0; Infinix X608 Build/OPR1.170623.032; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/92.0.4515.159 Mobile Safari/537.36"
	#<-----------[RANDOM SYSTEM]--------->
	lol = random.choice([a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18,a19,a20,a21,a22,a23,a24,a25,a26,a27,a28,a29,a30,a31,a32,a33,a34,a35,a36,a37,a38,a39,a40,a41,a42,a43,a44,a45,a46,a47,a48,a49,a50,a51,a52,a53,a54,a55,a56,a57,a58,a59,a60,a61,a62,a63,a64,a65,a66,a67,a68,a69,a70,a71,a72,a73,a74,a75,a76,a77])
	ugen.append(lol)
	#=================[START NOW]================#
